services:
  server:
    build:
      context: ./server
    restart: "always"
    ports:
      - "3001:3001"
    networks:
      - networkA
  postgres:
    build:
      context: ./database
      args:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_VERSION: ${POSTGRES_VERSION}
        POSTGRES_PORT: ${POSTGRES_PORT}
    restart: always
    # ports:
    #   - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-storage:/var/lib/postgressql/data
    networks:
      - networkA
volumes:
  postgres-storage:

networks:
  networkA: