services:
  server:
    build:
      context: ./server
    environment:
      PG_HOST: postgres
      PG_USER: ${POSTGRES_USER}
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      PG_DATABASE: ${POSTGRES_DB}
      PG_PORT: ${POSTGRES_PORT}
    restart: "always"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - networkA
  postgres:
    build:
      context: ./database
      args:
        POSTGRES_VERSION: ${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-storage:/var/lib/postgressql/data
    networks:
      - networkA
volumes:
  postgres-storage:

networks:
  networkA: